name: example
description: "Coral XYZ Anchor Dart client example - Counter DApp demonstrating Solana program interaction"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  solana: ^0.31.2+1
  borsh: ^0.3.2
  bs58: ^1.0.2
  coral_xyz: ^1.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/idl.json
